### ISSUE TITLE
在运行mnist_softmax.py是遇到了一些问题，希望同学能够帮助解答一些

### ISSUE THREAD

**Issue by wenmangayao** [wlmnzf/tensorflow-train#1]
代码如下
`Traceback (most recent call last):
  File "mnist_softmax.py", line 40, in <module>
    mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True)
  File "/home/liushiyao/tensorflow-train/mnist/input_data.py", line 201, in read_data_sets
    local_file = maybe_download(TRAIN_IMAGES, train_dir)
  File "/home/liushiyao/tensorflow-train/mnist/input_data.py", line 38, in maybe_download
    if not tf.gfile.Exists(work_directory):
AttributeError: 'module' object has no attribute 'gfile'`

**Comment by wlmnzf** [comment]
这个是版本的问题吧，之前用0.6的tensorflow也出这个问题，升级以后用的是0.7的版本，就ok了，请参考
